### ISSUE TITLE
Add Travis sensors

### ISSUE THREAD

**Issue by pinkywafer** [pinkywafer/Home-Assistant_Config#17]
Ref:
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/travis.yaml.disabled

**Comment by pinkywafer** [comment]
@CCOSTAN Do you have this working with your config? - I have the token in secrets (from github, with the specified scopes), but I'm not getting any sensors added at all.  Tried with invalid api key and I get the "Not a travis user" notification

**Comment by CCOSTAN** [comment]
Just got it working. 
![image](https://user-images.githubusercontent.com/2160436/88084681-c3be3200-cb52-11ea-8edf-58e62e7627eb.png)

Had to create a new GITHUB API token. 
https://www.home-assistant.io/integrations/travisci/
Once I did that, it worked.

**Comment by pinkywafer** [comment]
I've tried existing github personal access token for github API
now I've tried a new token also (both with the scopes set as documented...
sensor config:
```yaml
sensor:
  - platform: travisci
    api_key: !secret travis_github_token
    monitored_conditions:
      - state
    scan_interval: 10
```
still nothing!

**Comment by pinkywafer** [comment]
also tried the token with and without quotes

**Comment by CCOSTAN** [comment]
Hmm.. I created a new personal token. 
![image](https://user-images.githubusercontent.com/2160436/88088398-4e556000-cb58-11ea-9159-9e61ebb2ce20.png)

When you log into [TRAVIS-CI.ORG](https://travis-ci.org/account/repositories), is your GitHub account merged?
![image](https://user-images.githubusercontent.com/2160436/88088601-abe9ac80-cb58-11ea-9e88-4e4c08fe46eb.png)
I'm not using any quotes for the API.

**Comment by CCOSTAN** [comment]
Also, something silly that tripped me up was searching for 'travis' in the entity column and not the attribute column. 
![image](https://user-images.githubusercontent.com/2160436/88088858-16025180-cb59-11ea-8a15-373690aae557.png)

**Comment by pinkywafer** [comment]
checked... definately linked
just no travis sensors anywhere!

**Comment by CCOSTAN** [comment]
still getting the user error though? or just no sensors now?
Hmm.. looks like you are not the only one..
https://community.home-assistant.io/t/travisci-platform-configured-but-no-entities-are-being-added/143339/4

Maybe try defining the repo specifically. 
```yaml
  - platform: travisci
    api_key: !secret github_key
    repository:
      - home-assistant
    branch:
      - master
    monitored_conditions:
      - last_build_state
      - state
```
