### ISSUE TITLE
Trigger new Travis build on new HA version available

### ISSUE THREAD

**Issue by pinkywafer** [pinkywafer/Home-Assistant_Config#21]
Travis builds are normally triggered by commits/pr to the repo. When a new Home Assistant version becomes available, trigger a Travis build against the new version of home Assistant. 
This will validate config automatically before the new version is installed.

**Comment by pinkywafer** [comment]
Trigger build using Travis rest API:
https://docs.travis-ci.com/user/triggering-builds/

**Comment by pinkywafer** [comment]
+ Add build status to update notifications, so that build status is evident before installation

**Comment by pinkywafer** [comment]
rest command to trigger build:
```yaml
rest_command:
  travis_build:
    url: https://api.travis-ci.org/repo/pinkywafer%2FHome-Assistant_Config/requests
    method: POST
    headers:
      authorization: !secret travis_api_key
      Content-Type: "application/json"
      Accept: "application/json"
      Travis-API-Version: 3
    payload: '{"request": {"branch":"master"}}'
```
