### ISSUE TITLE
Addon Updates available reporting incorrectly

### ISSUE THREAD

**Issue by pinkywafer** [pinkywafer/Home-Assistant_Config#40]

**Comment by pinkywafer** [comment]
this is pulled by:
```yaml
command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"addons":[.data.addons[] | select(.version != .installed)]}'''
```

it appears that the params have changed:
```yaml
- name: Mosquitto broker
  slug: core_mosquitto
  description: An Open Source MQTT broker
  state: started
  version: '5.1'
  version_latest: '5.1'
  update_available: false
  repository: core
  icon: true
  logo: true
```
`installed` appears to have been replaced by `version`
`version` appears to have been replaced by `version_latest`
so these will also need to be used in the notifications
`.update_available == true` could be used in the `select` statement
