### ISSUE TITLE
migrate to Travis-ci.com

### ISSUE THREAD

**Issue by pinkywafer** [pinkywafer/Home-Assistant_Config#41]
Travis-ci.org is closing at the end of december 2020  get everything related migrated over to travis-ci.com
##Required steps
* [x] Migrate Travis from org to com
* [x] Update travis sensor
* [x] Update travis build rest command
* [x] Update build status badge on readme

**Comment by pinkywafer** [comment]
it appears that now the repo is moved to com, the repo is only found if I specify the repo in the config where previously it was found automatically

**Comment by pinkywafer** [comment]
badge appears to already be using .com

**Comment by BeardedTinker** [comment]
Can you pull status of Travis-CI build back in HA after migrating to .com version using integration? 
I've been fighting with this last 10 days and not sure if the API it's using is for .org version only.

**Comment by pinkywafer** [comment]
Initially, i got no return from the Travis sensor. I then added the repo name to the config and it seemed to work. However, the sensor data is historic from the last build on .org

I'm looking further into it, however i expect the problem is with the integration... It uses the travispy library which has not been active for a while now. I'm going to have a look into options, but at the moment i think it's a choice of
* work on the integration / travispy.
* Work on a custom component
* Try to use a rest sensor instead

I'm not sure what the best option will be, but I expect the last will prove the easiest!

**Comment by pinkywafer** [comment]
Rest sensor for new Travis:

```yaml
sensor:
  - platform: rest
    name: Travis-Ci Home Assistant Config
    resource: https://api.travis-ci.com/repo/pinkywafer%2FHome-Assistant_Config/builds?limit=1
    method: GET
    payload: '{"branch":{"name":"master"}}'
    headers:
      authorization: !secret travi_api_key
      Content-Type: "application/json"
      Accept: "application/json"
      Travis-API-Version: 3
    value_template: '{{value_json.builds.0.state}}'
    json_attributes_path: "$.builds.[0]"
    json_attributes:
      - number
      - started_at
      - finished_at
      - duration
      - previous_state
      - commit
```
@BeardedTinker this should get you going!
